---
title: "Introduction"
output: 
    html_document:
      number_sections: no
      toc: yes
      toc_float: yes
---

# Some motivating examples

* Example we'll be working towards in this workshop: map of railways & secondary sector employment in England 1851 in [static](output/england_1851_map_final.png) and [interactive](output/map_manchester.html) versions.
* Some examples of thematic maps from a [previous workshop](https://workshop.mhermans.net/thematic-maps-r/04_plot.html#add_layers_using_objects).
* More examples made with `tmap`, the R package we will be demonstrating [are online](https://github.com/mtennekes/tmap).
* Example [online press release](https://hiva.kuleuven.be/nl/nieuws/nieuwsitems/bruto-jobtoename-en-afname-in-beeld-voor-de-Belgische-regios-en-provincies) HIVA - KU Leuven with a interactive map on KU Leuven-website.


# Why (not) R for making maps?

| Why R | Why **not** R |
| ----- | --------------|
|       | Learning curve / no GUI |
| free & open source | |
| large community & ecosystem  | |
| very broad range of libraries | very broad range of libraries (docs) |
| statistical programming language | statistical programming language |

Alternative for example: dedicated GUI-driven GIS-software such as [QGis](https://www.qgis.org/).

With R ecosystem & programming background:

* Stronger focus on 'data science': collecting, reading, manipulating, visualising, communicating about data beyond the 'traditional' reporting of statistical analyses. More info: [tidyverse](https://www.tidyverse.org/), ["[R for Data Science](https://r4ds.had.co.nz/)". 
* Spatial data is treated in analysis like a regular dataframe (with a 'geometry' column): spatial analysis & "regular" analysis(skilss) move closer [more info: [simple features-standard in R](https://r-spatial.github.io/sf/index.html)

Consequences:

* Enables quick spatial data-exploration in single program & work-flow.
* Novel ways of approaching, using, presenting (esp. digital, large scale) datasources.

Example of novel applications using R to combine quering API's, spatial operations, visualising on externally provided interactive maps, etc.: [Exploring historical maps and spatial data with R and OpenStreetMap](https://mhermans.net/post/mapping-leuvense-gangen/).

# Worked example in this workshop: rail and industry in 1851 England

Data-source: *The occupational structure of Britain 1379-1911*, [Cambridge Group for the History of Population and Social Structure](https://www.campop.geog.cam.ac.uk/research/occupations/).

We will illustrate throughout example common steps for thematic maps:

1. Load spatial data.
2. Load and add "regular" data-of-intrest.
3. Manipulate (spatial) data.
4. Plot map.